version: 2

sources:
  - name: streamkap_mt5demo  # The name of the source
    database: data-tribe-sandbox-438709
    schema: streamkap_mt5demo  # The dataset name
    tables:
      - name: mt5_accounts  # The name of your table in Project A
        description: "Sample mt5_account table"
  - name: estuary_mt5demo_p01_ts02  # The name of the source
    database: data-tribe-sandbox-438709
    schema: estuary_mt5demo_p01_ts02  # The dataset name
    tables:
      - name: mt5_deals_2024  # The name of your table in Project A
        description: "Sample mt5_account table"